seiyria/bootstrap-slider

js/bootstrap-slider.js
Fixes issue #286. Adds translate css transform component in parent offset computation in _offset method. This particularily solves issues when using both iScroll and bootstrap-sliders as iscroll use css transforms to move scrollables around.
=> Fix for issue #286: Accounts for translate css transform in _offset function

index.html, js/bootstrap-slider.js
Above image is bug-reproducing-demo from e4ec897 which I just set `tooltip.opacity=1` forcefully.
In current version, these tooltips are draggable **even when they are invisible**.
I think it is OK for `tooltip-main (center)` and `tooltip-min` to be draggable on hidden because they are very near slider UI, but not torelable for `tootip-MAX`, so I fixed `tootip-MAX`'s top position.
=> Fix range-slider bug (index.html Example 2) where hidden but touchable tooltip-max moves up too high.

css/bootstrap-slider.css, js/bootstrap-slider.js, less/bootstrap-slider.less, sass/slider.scss, test/specs/LeftAndRightTrackSpec.js, tpl/SpecRunner.tpl, tpl/index.tpl
This adds left and right track segments that can be targeted by CSS (with .slider-track-left and .slider-track-right, respectively).  It allows users to style the "unselected" part of the slider, which is useful if you're building a "red-amber-green" style slider.
jsfiddle: http://jsfiddle.net/qfjjv2vp/
=> Add left/top and right/bottom track segments so they can be styled independently

js/bootstrap-slider.js
Calculated slider offsets are incorrect when the body has a margin of auto - resulting in an offset in display when you initiate the drag and where the handle ends up being displayed. 
I've changed the do..while loop with offsetParent to use getBoundingClientRect() and it appears to fix the issue.
Broken Example: http://jsfiddle.net/0rh54yxo/1/
Working Example (using getBoundingClientRect): http://jsfiddle.net/0rh54yxo/6/
=> Calculated offsets incorrect when body has a margin of auto

js/bootstrap-slider.js
The .value property of the element was not changed by the _setDataVal function. Therefore it was not possible to get the correct input's value by accessing the element.
=> fix: js-accessible value was not changed by slider function

js/bootstrap-slider.js
Use camelCase syntax for style names instead of separating words with
dash like in CSS. It works better in some non-bleeding-edge browsers,
for example Firefox ESR / Iceweasel (31.x.x).
The same syntax is used in _css() helper function replacement.
=> Fix tick labels for some browsers

README.md, index.html, js/bootstrap-slider.js, test/specs/FocusOptionSpec.js, tpl/index.tpl
I think the way ``_triggerFocusOnHandle()`` was used before (in ``_mousedown()``),
i.e. without any arguments, was unintended in the first place. Now, it is called with
the appropriate slider number after the value change took place if the ``focus``
option is ``true``.
Also updated docs and index template.
I don't think that a unit test is required here.
When this PR is accepted, #330 is fixed and can be closed.
=> Add focus option.

js/bootstrap-slider.js
Small change to trigger the slideStop event after the setDataVal, instead of before.
This fixes the issue #369
=> Changed the order of the slideStop event, moved right after dataSetVal issue #369

package.json
In order to use bootstrap-slider with tools like [Parcelify](https://github.com/rotundasoftware/parcelify) and [Sheetify](https://github.com/sheetify/sheetify), the `package.json` file needs a `style` field referring to the correct CSS file. Bootstrap itself, for example, already has this.
=> Add style field to package.json

js/bootstrap-slider.js, test/specs/LogarithmicScaleSpec.js
Fixes #419 
Hi there - I changed the tick positions to follow whatever percentages the current scale uses - it was previously only positioning ticks by linear scale.
Here's a JSFiddle with the fix shown
https://jsfiddle.net/ppdtt6cz/3/
I added a test, and also made a small edit to another logarithmic test description to better indicate what it is testing.
=> Fix tick mark position in logarithmic scale

css/bootstrap-slider.css, js/bootstrap-slider.js, less/rules.less, sass/slider.scss, test/specs/TickLabelSpec.js
Using the slider in vertical orientation with labels has the labels rendering in the incorrect location. The fix renders the labels in a more appropriate position when using the slider in vertical orientation.
Original
http://jsfiddle.net/seshi/mh3d14ze/
Fix
http://jsfiddle.net/seshi/smogd9mk/
=> Fix label positions when using slider in vertical orientation.

README.md, js/bootstrap-slider.js, test/specs/AccessibilitySpec.js, tpl/SpecRunner.tpl, tpl/index.tpl
Currently the values are not read back to screenreaders, I've tried to add some accessibility based off http://www.oaa-accessibility.org/examplep/slider1/.
Example: http://jsfiddle.net/f2xsjc0j/1/
Before:
After:
=> Better accessibility

js/bootstrap-slider.js, test/specs/TickClickingBehaviorSpec.js
When _ticks_positions_ are specified, the _raw_value_ calculated based on the percentage should not be adjusted with the _min_ value.
Changes:
* Do not adjust with base (min) after calculated with ticks positions
* Add example 13.a in index.html for the case above
=> Update how slider value is adjusted based on ticks positions

js/bootstrap-slider.js, test/specs/EventsSpec.js, test/specs/ResizeSpec.js, tpl/SpecRunner.tpl
A number of solutions have been proposed to make the slider labels responsive, this was the most elegant one I've seen, originally proposed in [this thread](https://github.com/seiyria/bootstrap-slider/issues/464).
A visual example of the change can be seen [here](http://jsfiddle.net/zsiswick/76sywz9d/2/). Please try expanding and contracting the result window. Note the responsive labels work for vertical slider orientation as well.
=> Bind _layout() function to window.resize event

src/js/bootstrap-slider.js, test/specs/TooltipPositionOptionSpec.js
Solution for problem when using range and tooltip position set to bottom.
The max tooltip is at top instead of bottom.
See fiddle:
https://jsfiddle.net/b8jtpb0e/
Code changed
```javascript
if (this.options.tooltip_position === 'bottom') {
if (offset_min.right > offset_max.left) {
this._removeClass(this.tooltip_max, 'bottom');
this._addClass(this.tooltip_max, 'top');
this.tooltip_max.style.top = -14 + 'px';
} else {
this._removeClass(this.tooltip_max, 'top');
this._addClass(this.tooltip_max, 'bottom');
this.tooltip_max.style.top = this.tooltip_min.style.top;
}
}
else {
if (offset_min.right > offset_max.left) {
this._removeClass(this.tooltip_max, 'top');
this._addClass(this.tooltip_max, 'bottom');
this.tooltip_max.style.top = 18 + 'px';
} else {
this._removeClass(this.tooltip_max, …
```
=> Fix for tooltip postion bottom on range slider

src/js/bootstrap-slider.js, test/specs/EventsSpec.js
this simple patch sets the input's value attribute
to the new value _before_ triggering events.
it works around the issue of reading the input's 
value attribute (`$(input).val()`) inside an event listener
which would always return the value of the preceding slide step.
so, the following inside an event listener will evaluate to `true`:
```js
event.value.newValue == input.value;
```
=> fix event/input value attribute "race condition"

src/js/bootstrap-slider.js, test/specs/ScrollableBodySpec.js, test/specs/ScrollableContainerSpec.js, tpl/SpecRunner.tpl
Works fine with body scrolled down.
Per your request, added simple test even for the case when <body> element is scrolled down before interacting with slider.
=> Fix for vertical slider in Y-scrollable elements after scroll.

README.md, src/js/bootstrap-slider.js, test/specs/AutoRegisterDataProvideSpec.js, tpl/SpecRunner.tpl, tpl/index.tpl
This PR activates automatic registering of `<input />` Elements when they are equipped with a `data-provide="slider"` Attribute. This conforms to the way other Bootstrap-Plugins like [bootstrap-datepicker](https://bootstrap-datepicker.readthedocs.org/en/latest/#data-api) work and mimics the Behavior of Bootstrap's own JavaScript-Plugins, ie [Buttons](http://getbootstrap.com/javascript/#buttons) which are enabled by `data-toggle="button"` or similar Attributes.
All Slider-Options can be set with `data-slider-` Attributes, so in most Situations no custom JavaScript-Code would be required anymore.
=> Auto register data provide

src/less/rules.less, src/sass/slider.scss
Found a minor CSS issue. Seems bootstrap is giving class tooltop-inner a max width. Those with design-eyes might notice that larger labels won't be centered properly when given an explicit width.
With max-width: 200px
Without: 
Solution is simple, set max-width to none. Developers can still set a width or max-width later in their stylesheets if they wish to override.
=> unset the max-width of the slider

src/js/bootstrap-slider.js, test/specs/PublicMethodsSpec.js, tpl/SpecRunner.tpl, tpl/index.tpl
If a slider is initially hidden (fior example inside a Bootstrap-Tab or any other `display:none` Container) one ought to call `.relayout`, so that the Slider can update the layout with the now available information (for example, most browsers report a width of 0 before the content is actually shown).
This leads to an issue, that is not yet handled in `.relayout()`:
1. After the initialization of a hidden slider, `this._state.size` is 0
2. Calling `.relayout()` after making it visible, internally calls `._layout()` which, among other things, recalculates the tick-lable size `labelSize`
3. because `labelSize` is calculated based on `this._state.size`, all labels will also have a width of 0 and be displayed incorrect
This PR adds an additional call to `._resize()` into the body of the …
=> Recalculate size on relayout

src/js/bootstrap-slider.js, test/specs/EventsSpec.js
Fixing issue #428 where scrolling on mobile devices are locked in the slider.
Here's the fixed version in demo: http://codepen.io/jerrylow/pen/wGrBVo
Also the previous issue with video demonstration:
Codepen: http://codepen.io/anon/pen/LVKeQq
Video: http://jerrylow.com/demo/bootstrap-slider/bootstrap-slider-demo.mp4
Changes:
I'm detecting the direction of the swipe before determining if they're trying to scroll or swipe on the slider. There's a threshold if they stay within 5px (+/-) of the slider direction also moving a distance greater than 15px. I did a bunch of tests with 5, 10, 15, 20, 25. Anything greater than 20 there was a bit of delay so it wasn't as responsive. Ten was ok but there's still an issue if the user is swiping slightly diagonal. Fifteen pixels seems to be the best …
=> Touch move conflicting with user trying to scroll fix

src/js/bootstrap-slider.js, test/specs/DraggingHandlesSpec.js
Fix #547 issue where when range sliders overlap then clicking on the left moves the max handle to the left of the min handle.
=> Fix range slider swapping place on click

src/less/rules.less, src/less/variables.less, src/sass/_rules.scss, src/sass/_variables.scss
Adds LESS & SASS variables to control the width of the slider. It defaults to 210px (the currently hardcoded value) but can be overridden.
See #566 for a case that might be resolved with this change.
=> Add variables to control slider width and height

tpl/index.tpl
- Addresses: https://github.com/seiyria/bootstrap-slider/issues/564
Pull Requests
=============
=> add example for intializing slider via 'data-provide' attribute

README.md, package.json, scripts/release.sh
@seiyria 
I am attempting to refactor our release script a little bit.
One thing that always bothered me was the fact that we were always off by one patch bump when we published to npm.
So instead of having the version be bumped separately from the `gh-pages` build, `/dist` build, and `npm publish`, I figured we could just combine all of those into a script and then proxy it with the `npm run release` command. i tested it locally and it works great, but let me know what you think.
Thanks!
=> refactor postpublish script into all-in-one release script

src/js/bootstrap-slider.js, src/less/rules.less, src/sass/_rules.scss, test/specs/ElementDataAttributesSpec.js, test/specs/KeyboardSupportSpec.js, test/specs/PublicMethodsSpec.js, test/specs/TickMarksSpec.js
Implements the suggestion made by @phazei in: https://github.com/seiyria/bootstrap-slider/issues/500
This PR wraps all of the ticks within a single container element as opposed to being within the `.slider-track` element. This enables individual ticks to be more easily targeted with CSS selectors such as `nth-of-type(n)`
**Screenshot:**
Pull Requests
=============
=> Tick mark container

README.md, src/js/bootstrap-slider.js, test/specs/NamespaceSpec.js
Addresses: https://github.cleom/seiyria/bootstrap-slider/issues/575
After thinking about it more, I still want people to use the `$.fn.slider` namespace when possible, so I will not update the rest of the docs.
However, the plugin will always bind to the alternate namespace and will print a console warning when the main namespace is already reserved
Pull Requests
=============
=> Namespace updates

src/js/bootstrap-slider.js, test/specs/RangeHighlightsSpec.js, tpl/SpecRunner.tpl
=> Range highlights should reflect options.reversed when set

README.md, src/js/bootstrap-slider.js, test/specs/TooltipMouseOverOptionSpec.js, tpl/index.tpl
=> hover over ticks to view their value

src/js/bootstrap-slider.js, test/specs/DestroyMethodTests.js
Fixes https://github.com/seiyria/bootstrap-slider/issues/640
=> Bug-fix: set this.eventToCallbackMap property values to undefined instead of null on destroy()

README.md, src/js/bootstrap-slider.js, test/specs/PublicMethodsSpec.js
=> Validation fix to allow for string numbers

README.md, src/js/bootstrap-slider.js, test/specs/AriaValueTextFormatterSpec.js, tpl/SpecRunner.tpl
Pull Requests
=============
**Original issue** : Feature Request : aria-valuetext as formatter value
https://github.com/seiyria/bootstrap-slider/issues/641
**Example of feature in action**:
https://fiddle.jshell.net/bbw6z63n/4/
Issue #641
=> aria-valuetext as formatter value

src/js/bootstrap-slider.js, test/specs/PublicMethodsSpec.js
=> Removes 'none' classes after selection change

src/sass/_rules.scss
Sorry, I noticed that PR #663 was wrong. I forgot to rename @slider-line-height into $slider-line-height.
This PR fix it I now it works well.
Sorry for that.
=> fix PR #663

dist/bootstrap-slider.js, src/js/bootstrap-slider.js
Issue #339: Modal dialog closes when dragging and releasing mouse button outside dialog.
Bootstrap modal needs a mousedown event to check the modal needs to be closed. When you release the mouse, if mouse was on modal, there will be no exit. But in our situation bootstrap-slider prevents bubbling mousedown event to modal, so it closes when you finished mouse movement outside modal.
before:
after:
=> Prevent bootstrap modal hiding

README.md, src/js/bootstrap-slider.js, src/less/rules.less, src/sass/_rules.scss, test/specs/RtlOptionsSpec.js, tpl/SpecRunner.tpl, tpl/index.tpl
=> Feature : rtl mode (with options)

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, README.md, package.json, test/specs/KeyboardSupportSpec.js, test/specs/LogarithmicScaleSpec.js, test/specs/NamespaceSpec.js, test/specs/PublicMethodsSpec.js, test/specs/ResizeSpec.js, tpl/SpecRunner.tpl
Addresses https://github.com/seiyria/bootstrap-slider/issues/696
Fixed the test suite by upgrading the grunt-contrib-jasmine plugin to the latest version, which uses a version of PhantomJS that does not throw an error on OSX.
This also upgrades us to Jasmine 2.x.x...finally get `done()` callbacks for async unit tests!
Pull Requests
=============
=> Fixes test suite and upgrades to Jasmine 2.x.x

README.md
I have created Vue.js bindings so Vue.js users can also easily use the `bootstrap-slider` without too much efforts
=> Added link to Vue.js bindings

src/js/bootstrap-slider.js, test/specs/StepReachMaxValueSpec.js
gracefully handle max value when a step size is defined and the max v…alue does not fit the step size
=> Max value calculation wrong due to cutoff when max value is not a multiple of step

src/less/rules.less, src/less/variables.less, src/sass/_rules.scss, src/sass/_variables.scss
Pull Request Referencing #778 
=============
Requesting pull for branch that uses variables in place of hardcoded values for the control colors.  Additionally, brand-primary is used.  bootstrap variables file is already a dependency of bootstrap-slider.less by use of `@line-height-computed` in variables.less, so that just uses the `@brand-primary` variable.  For the SASS file, it either uses the `$brand-primary` variable if it exists or it uses a default of `#0480be`.
Feel free to tweak the colors as needed.  Otherwise, if they need adjusted, I can make the changes in another commit too.
=> switched to using variables for the colors

src/js/bootstrap-slider.js, src/less/rules.less, test/specs/PublicMethodsSpec.js
Fix #483 using CSS property `transform` instead of `margin-*` for the tooltips.
According to [caniuse.com](http://caniuse.com/#search=transform), this property has a very good support in the browsers.
=> Use `transform: translate()` instead of margin-* for the tooltips. Fix #483

README.md
just removed a trailing ; in webpack config example
=> fixed typo in js example

src/less/rules.less, src/sass/_rules.scss
=> Show pointer cursor over slider handle

README.md, src/js/bootstrap-slider.js, test/specs/LogarithmicScaleSpec.js, test/specs/StepReachMaxValueSpec.js
The prior implementation required values > 0 for proper operation; by offsetting to values starting at 1, any range can be used with the logarithmic scale.
Resolves #835 
JSFiddle example: https://jsfiddle.net/j1LLdrhq/5/
Pull Requests
=============
=> Allow any value range on logarithmic scale

src/less/rules.less, src/sass/_rules.scss
I'm now updating from a very old version of this package, and I found that this CSS rule got removed somehow.  In my application, all the possible options are marked with ticks, and the ticks are clickable.  Yet the `cursor: pointer` rule somehow only applies everywhere *except* the tick marks (probably because of a change in how the tick marks are `position`ed).  Thus I found it necessary to make the tick marks also have the `cursor: pointer` rule.
Here's a screenshot of my use-case.  Unfortunately, I can't get the screenshot to show the cursor, but it is correct.
=> Use pointer cursor on slider ticks

src/less/rules.less, src/sass/_rules.scss
refs #629
Pull Requests
=============
=> 629: Hovering next to slider does not show the tooltip.

src/js/bootstrap-slider.js, test/specs/DraggingHandlesSpec.js
Pull Requests
=============
This pull request fixes https://github.com/seiyria/bootstrap-slider/issues/854. You can check the issue for my JSFiddle that is used to reproduce the bug.
I added 2 unit tests as well as making a minor edit with a unit test in the same file: `test/specs/DraggingHandlesSpec.js`.
I will say that I was getting this error `Fatal error: Callback must be a function` displayed at the very end in red text, after running the unit tests using `grunt test` command. I don't know why, thoughts?
=> Fix Issue #854 - Range slider, min value over max value.

tpl/index.tpl
Pull Requests
=============
Details
=============
Fixes issue #867
=> Fix typo in Boostrap-Slider API Example page

tpl/index.tpl
Pull Requests
=============
Details
=============
Fixes issue #868 
I fixed the `tick_positions` array and I made is so that the slider is not in "reversed" mode.
=> Fix Issue #868 Typo in example 14

src/js/bootstrap-slider.js
Pull Requests
=============
Details
=============
Fixes issue #865 
I just removed the duplicate call to `_layout()` inside the `relayout()` function because `_resize()` already makes a call to `_layout()`.
=> Fix `relayout()` making a duplicate call to `_layout()`

src/js/bootstrap-slider.js, test/specs/TickLabelSpec.js
Pull request for #751 
--
Adds class `label-in-selection` if tick labels are in the selection range.
Adds class `label-is-selection` if tick label is selected, min or max.
--
_figure 1. example, selection tick labels are in darker font_
=> Add selection CSS classes to tick labels

src/js/bootstrap-slider.js
Hello, when using this library in a front-end that was exposed via an iframe I ran into a long standing firefox bug where `getComputedStyle` would return null. https://bugzilla.mozilla.org/show_bug.cgi?id=548397
This is the workaround I implemented to work-around this issue.  Very recently, this bug has finally been [resolved ](https://bugzilla.mozilla.org/show_bug.cgi?id=1467722) in version 62, but I still figured it would be worth contributing considering the bug could still be hit on the last ~9 years of firefox releases.
Let me know if unit-tests / a JSFiddle is required for this fix and I'll see what I can do, I'm not quite sure if I could reproduce the same iframe-dependent behavior in a JSFiddle at this point.
Pull Requests
=============
Please accompany all pull requests with the …
=> Don't access null result from getComputedStyle

src/js/bootstrap-slider.js, test/specs/DraggingHandlesSpec.js
fixes #392
Pull Requests
=============
=> allow range slider to snap bounds.

src/js/bootstrap-slider.js
Fixes #882 
Since the `_state` is relatively small, I just simply copied over the keys and values. But I'm not sure where to put the `_copyState()` function though. Any suggestions?
I will add a unit test as well.
Pull Requests
=============
=> Add '_copyState()' function

src/js/bootstrap-slider.js, test/specs/KeyboardSupportSpec.js
Fixes #878 
I'll add unit tests later.
You can check the JSFiddle in the issue.
Pull Requests
=============
=> Properly check if the slider values have changed

src/js/bootstrap-slider.js, test/specs/AriaValueTextFormatterSpec.js
Fixes #799 
Pull Requests
=============
=> Fixes Issue #799: valuetext doesn't update

test/specs/PublicMethodsSpec.js
=> Fix #887 doesn't destory the silder instance cause "generates mutiple silder instance" test failed

src/js/bootstrap-slider.js, test/specs/DraggingHandlesSpec.js, test/specs/EventsSpec.js, test/specs/StepReachMaxValueSpec.js, test/specs/TickClickingBehaviorSpec.js, test/specs/TooltipMouseOverOptionSpec.js
Make _mouseup get value from event and perform the same as _mousemove and _mousedown. #824
=> Fix the bug of _mouseup passing wrong value.

src/js/bootstrap-slider.js, test/specs/ElementDataAttributesSpec.js
I wrote unit tests for checking if `_setDataVal()` works properly.
It's going to be a bit more difficult to write tests to check if removing the calls to `_layout()` haven't broken anything.
Pull Requests
=============
=> Remove extra calls that are unnecessary

src/js/bootstrap-slider.js, test/specs/KeyboardSupportSpec.js
The percentage values were being miscalculated.
Old equation was taking into account negative min values.
Wrong
`(val / this.options.max) * 100;`
Correct
`((val - this.options.min) / (this.options.max - this.options.min)) * 100;`
```
min, max = -100, 100
val = 10
// old
percentage
= (10 / 100) * 100
= 10%
// fix
percentage
= [ (10 - (-100)) / (100 - (-100) ] * 100
= [ (10 + 100) / (100 + 100) ] * 100
= 110 / 200 * 100
= 55%
```
So I just make call to `this._toPercentage()`.
=> Fix calculation of percentage values

src/js/bootstrap-slider.js, test/specs/TickMarksSpec.js
Fixes #690 
Pull Requests
=============
=> Fixes Issue #690 ticks should not overwrite min/max settings

src/js/bootstrap-slider.js
Fixes #875 
https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L258-L267
This line should convert the value to a float/double if the `step` is also a float/double.
https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L259
Pull Requests
=============
=> Remove unnecessary call to parseFloat()

src/js/bootstrap-slider.js, test/specs/AriaValueTextFormatterSpec.js, test/specs/DestroyMethodTests.js, test/specs/EventsSpec.js, test/specs/LogarithmicScaleSpec.js, test/specs/NamespaceSpec.js, test/specs/TickMarksSpec.js
I noticed these two lines were incorrect. The slider instance that is added/removed should be based on the namespace, either: _slider_ or _bootstrapSlider_.
https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L995
https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L1064
I added unit tests.
I also fixed some unit tests that were not properly destroying the `<div>` slider element. This caused some unit tests to fail when it used `.siblings()` to check the `<div>` slider element, but the method also collects more than 1 `<div>` if they exist, which was causing hard to track bugs.
Pull Requests
=============
Please accompany all pull requests with the following …
=> Fix namespace handling

src/js/bootstrap-slider.js, test/specs/TooltipMouseOverOptionSpec.js
Fix typo with variable name. Just added `_` underscore.
Changed `this.alwaysShowTooltip` to `this._alwaysShowTooltip`
https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L809-L812
https://github.com/seiyria/bootstrap-slider/blob/88dfe2aa20bb49f524b681062e6ea15d26402c41/src/js/bootstrap-slider.js#L1164-L1171
Added a unit test.
Also there was a bug when `options.tooltip` was set to `'always'` and the `options.ticks_tooltip` was set to `true`.
Pull Requests
=============
=> Fix tooltip when option is set to 'always'

src/js/bootstrap-slider.js, test/specs/TooltipMouseOverOptionSpec.js
Fixes #884 
This displays the correct value for the tick and correctly positions the tooltip above the tick.
Will add unit tests.
Pull Requests
=============
=> Fixes Issue #884: Hovering over ticks displays the tick index

src/js/bootstrap-slider.js, test/specs/KeyboardSupportSpec.js
Pull Requests
=============
PR #879 / v10.3.4 introduced an issue for range sliders as a change event was only triggered when both lower and upper value changed. See https://github.com/pimlie/vue-bootstrap-slider/issues/11 for downstream issue. This PR fixes that.
=> fix: trigger change on either range value

src/js/bootstrap-slider.js, test/specs/DraggingHandlesSpec.js
Pull Requests
=============
This fixes #896
=> Bugfix mouseup trigger change

LICENSE.md, src/js/bootstrap-slider.js, src/less/bootstrap-slider.less, src/sass/bootstrap-slider.scss
happy new year! 🎉 
Pull Requests
=============
=> update references to 2019

README.md, src/js/bootstrap-slider.js, test/specs/LockToTicksSpec.js, tpl/index.tpl
=> lock_to_ticks

README.md, src/js/bootstrap-slider.js, test/specs/RefreshMethodSpec.js, tpl/index.tpl
Closes #901.
The user can pass an object with the property `useCurrentValue` set to
`true` so that the slider maintains its value after a call to `refresh`.
~~I will add an example as well.~~ Done.
Pull Requests
=============
=> Add new feature to persist the value after a refresh

src/js/bootstrap-slider.js, test/specs/EventsSpec.js, test/specs/TouchCapableSpec.js, tpl/SpecRunner.tpl
This pull request addresses these issues:
Page scrolling: https://github.com/seiyria/bootstrap-slider/issues/639
Passive listeners: https://github.com/seiyria/bootstrap-slider/issues/842
Tooltips not displaying on touch-enabled mobile devices:
https://github.com/seiyria/bootstrap-slider/issues/513
https://github.com/seiyria/bootstrap-slider/issues/765
* I removed the passive listener check because the intention is to stop the page from scrolling while dragging the slider on touch devices (Which was added here: https://github.com/seiyria/bootstrap-slider/pull/680)
* I've removed the initialization code and touch movement checks in `_touchstart()` and `_touchmove()` just to see if the code would work. @rovolution Is this code meant for browser compatibility and performance? …
=> Fix touch drag on mobile devices

README.md
I use webpack-encore in my projects. I found a way to use this plugin without jQuery.
Nota: works for now with BS5
Pull Requests
=============
=> Add webpack encore config

src/sass/_rules.scss, src/sass/_variables.scss
Pull Requests
=============
Makes mixin-based colors overridable in variables, so layout can be adapted more easily to custom layout that uses CSS variables.
=> Move mixin-based colors to variables
