seiyria/bootstrap-slider

css/bootstrap-slider.css
less/bootstrap-slider.less
sass/slider.scss

More closely follows the style of Bootstrap 3 (no opacity, uses same
colour of blue as btn-primary).

Removed opacity and changed colour of handles.

---

README.md
css/bootstrap-slider.css
index.html
js/bootstrap-slider.js
less/bootstrap-slider.less
test/specs/TickMarksSpec.js
tpl/index.tpl

Add tick marks to the slider. Two new configuration options have been
defined:
- ticks (Array): used to define the values of the ticks. Overwrites
min and max options.
- snap (int): Used to define snapping behaviour near tick marks.

(feat) Add tick marks

---

css/bootstrap-slider.css
js/bootstrap-slider.js
less/bootstrap-slider.less
sass/slider.scss

In the previous pull request #296  @rovolution noted I took the liberty to change the default styling of the track selection for all sliders. This fixes that issue :)

(fix) Track selection for ticks gets an extra selector

---

README.md
index.html
js/bootstrap-slider.js
test/specs/LogarithmicScaleSpec.js
tpl/index.tpl

This commit allows the scale to be changed from `linear` to
`logarithmic` using the newly introduced `scale` option.

(feat) Add logarithmic scale

---

js/bootstrap-slider.js

Use "Array.isArray" to check whether an object is an array

---

js/bootstrap-slider.js
test/specs/ElementDataAttributesSpec.js
tpl/SpecRunner.tpl
tpl/index.tpl

Changed underscores with dashes for correct getting data attributes values

Fixed getting options with complicated names from data attributes

---

index.html

This fixes the typo in closing the input element in example 6, discovered it when copy pasting example 6 into my code :)

Fix typo in code example 6

---

js/bootstrap-slider.js

Apologize if all my pushes were spamming anyone. Kept trying to get the damn white space to line up (looked fine in my editor).

Fix offset calculation when contained in relatively positioned parent. Fixes #340

---

js/bootstrap-slider.js
test/specs/TickMarksSpec.js

Bug producing wrong 'in-selection' ticks

Fix issue #356

---

Gruntfile.js
README.md
css/bootstrap-slider.css
index.html
js/bootstrap-slider.js
less/rules.less
package.json
test/specs/TickMarksSpec.js
tpl/index.tpl

- Add `ticks_positions` option (array)
- Current limitation: Does not work with logarithmic scale.

(feat) Add option to define position of ticks

---

js/bootstrap-slider.js
test/specs/LogarithmicScaleSpec.js

Added a test to make sure the step size was honored.

Honor step size on the logarithmic scale.

---

js/bootstrap-slider.js
test/specs/DraggingHandlesSpec.js
test/specs/LogarithmicScaleSpec.js
test/specs/RefreshMethodSpec.js

@seiyria; @severinmoussel this should resolve https://github.com/seiyria/bootstrap-slider/issues/407 and should better organize our internal state.
let me know if it all looks good and ill merged in.
Here is the updated fiddle to verify that #407 is resolved by this: https://jsfiddle.net/sntcry83/6/

Refactor internal state; Test coverage for refresh() error 407

---

js/bootstrap-slider.js
test/specs/ElementDataAttributesSpec.js

Should resolve https://github.com/seiyria/bootstrap-slider/issues/412
What are your thoughts @kozlitinaelja?

Convering 'data' attribute to be 'data-value' and directly set equal to the value

---

js/bootstrap-slider.js
test/specs/TooltipSplitOptionSpec.js

Fixes #418 
http://plnkr.co/edit/Nyw1kViPSrMO5OcVZB24?p=preview
cc @seiyria please merge quickly and release if good ;)

Correct splted tooltip position on init

---

js/bootstrap-slider.js
test/specs/PublicMethodsSpec.js

https://github.com/seiyria/bootstrap-slider/issues/232
hopefully everything is correctly done. never created such tests before, but test fails if null is set.

fixing tooltips on mouse leave

---

src/js/bootstrap-slider.js

Improves module definition and behaviour described in issue https://github.com/seiyria/bootstrap-slider/issues/578

Improve module definition

---

README.md
src/js/bootstrap-slider.js

Addresses: https://github.com/seiyria/bootstrap-slider/issues/589#issuecomment-232429818
Tagging @TomiS and @adambiggs for reference.
Pull Requests
=============

Revert amd change

---

LICENSE.md
composer.json
src/js/bootstrap-slider.js
src/less/bootstrap-slider.less
src/sass/bootstrap-slider.scss

Resolves https://github.com/seiyria/bootstrap-slider/issues/648

Updating license info

---

src/sass/_rules.scss

I compare the less and scss files and correct the scss to reflect the less file.
fix #662

fix scss rules based on less rules

---

tpl/index.tpl

Fixing "Without JQuery " example.

Fix example 6

---

.codeclimate.yml

Pull Requests
=============
- I started on a Code Climate config with ESLint, CSSLint and our duplication engine enabled. 
- It's currently using an inferred config for ESLint, but we can customize this to fit your project's needs.
- Our duplication engine is set to a slightly elevated mass_threshold. This can be fine-tuned as well!

Created a Code Climate config

---

README.md

Pull Requests
=============
Added a Code Climate badge to your README!

Update README with Code Climate badge

---

src/js/bootstrap-slider.js

Fix issue #687 with keyboard control of range slider.
JSFiddle: https://jsfiddle.net/pgzp515m/

Fix #687: Accessibility on range slider with keyboard control

---

src/sass/_rules.scss

Minor fix for sass, the mixin was used incorrectly.

Fix sass mixin usage

---

src/js/bootstrap-slider.js

I fixed the issue described in #746.

Fix selection of surrounding DOM elements while sliding in FF and IE

---

src/js/bootstrap-slider.js
test/specs/ScrollableBodySpec.js
tpl/SpecRunner.tpl

Fixes #594 
Should I tidy up the rest of the [spec file][sf]?
[sf]: https://github.com/seiyria/bootstrap-slider/pull/828/files#diff-73615cea1fe2d0803b81aebbac268f06

Fix determining mouse coords when pageXOffset >= 0

---

README.md

Added more info on how the alternative namespace works. I misinterpreted it when using this lib.

Change readme on alternative namespace

---

README.md

I suggest to add a note in the README about Bootstrap 4 compatibility until #689 is resolved because I think this is a blocker for most users.

Add note about Bootstrap 4 compatibility

---

src/js/bootstrap-slider.js
test/specs/KeyboardSupportSpec.js

Fixes #876 
I've added unit tests

Fixes Issue #876: Values for range slider are not the same

---

tpl/index.tpl

Hi, 
This PR is not to fix any bugs so I did not create any issue about it. I want to make all users easy to read this long page by creating some links.
I got some errors while I was trying to run the `npm install grunt-cli -g` command that you recommended in README file in my local machine. Those errors are about missing write access, so I could not run any unit tests. However, I tried to test my code online (www.w3schools.com) to make sure all links that are linking to the right parts and how the table look like. 
Here is a list of what I have done:
1. Created a table to store the link of all examples
2. Added CSS for that table
3. Added a link to back to top in each examples
Would you please review it? Please let me know if you want me to change something to make the UI look better. …

Created a table to store the link of all examples

---

src/js/bootstrap-slider.js
test/specs/PublicMethodsSpec.js

fix bridget bug with empty jquery object

---

CHANGELOG.md
README.md
tpl/index.tpl

adds release notes for v11.0.0
